function [header, data] = ZE_MeasRead( file, readMode )
% function [header, data] = ZE_MeasRead( file, readMode )
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% File:         ZE_MeasRead.m     
% Project:      Zühlke 
% Customer:     Zühlke
%
% Date:         10.03.2008 ... 23.08.2016
% Name:         Lukas Gaetzi
% Company:      Zuhlke Engineering Ltd.
% Version:      R2016a 
%
% Description:  Read a measurement file written by ZE_Recorder and return 
%               the header and data if required, depending on parameter 
%               'readMode'.
%
%               readMode = 'headerOnly' -> read only header
%               readMode = 'whole'      -> read header and data
%
%               The parameter 'file' contains the file including
%               pathname.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



%% Initialisations

header  = [];
data    = [];


%% read the header according to the file format

% open file 
fid = fopen( file );

% read the file format
strFormat = textscan( fid, '%s%s', 1, ...
                      'Delimiter', ';', ...
                      'HeaderLines', 1 );
fileFormat = char( strFormat{2} );

% read depending on file format
switch fileFormat
    
    case 'v1.0'
        
        disp(['Reading header, fileformat ' fileFormat ' ...']) 
        
        % read 7 more lines of header
        strHeader = textscan( fid, '%s%s', 6, ...
                              'Delimiter', ';', ...
                              'HeaderLines', 1 );
                          
        header.fileFormat       = fileFormat;
        header.project          = char( strHeader{2}(1) );
        header.sRate            = str2double( strHeader{2}(2) );
        header.nrOfSamples      = str2double( strHeader{2}(3) );
        header.startDate        = char( strHeader{2}(4) );
        header.startTime        = char( strHeader{2}(5) );
        header.description      = char( strHeader{2}(6) );
        header.operator         = char( strHeader{2}(7) );
                          
        % read header of data columns (they are part of the header)

        % read over newline characters
        strChannels     = fgetl( fid );             
        strChannels     = fgetl( fid );             

        % channel names
        strChannels     = fgetl( fid );             
        strChannels     = textscan( strChannels, '%s', 'Delimiter', ';' );
        header.channels = strChannels{1};

        % channel units
        strUnits        = fgetl( fid );             
        strUnits        = textscan( strUnits, '%s', 'Delimiter', ';' );
        header.units    = strUnits{1};

    case 'v1.1'     % v1.1 includes DAQmx names for automatic data processing
        
        disp(['Reading header, fileformat ' fileFormat ' ...']) 
        
        % read 7 more lines of header
        strHeader = textscan( fid, '%s%s', 7, ...
                              'Delimiter', ';', ...
                              'HeaderLines', 1 );
                          
        header.fileFormat       = fileFormat;
        header.project          = char( strHeader{2}(1) );
        
        % make sure that if csv file was generated with german XP,
        % that the comma is replaced with a decimal point
        samplingRate            = strrep( strHeader{2}(2), ',', '.' );
        header.sRate            = str2double( samplingRate );

        header.nrOfSamples      = str2double( strHeader{2}(3) );
        header.startDate        = char( strHeader{2}(4) );
        header.startTime        = char( strHeader{2}(5) );
        header.description      = char( strHeader{2}(6) );
        header.operator         = char( strHeader{2}(7) );
                          
        % read header of data columns (they are part of the header)

        % read over newline characters
        strChannels     = fgetl( fid );             
        strChannels     = fgetl( fid );             

        % channel names
        strChannels     = fgetl( fid );             
        strChannels     = textscan( strChannels, '%s', 'Delimiter', ';' );
        header.channels = strChannels{1};

        % channel units
        strUnits        = fgetl( fid );             
        strUnits        = textscan( strUnits, '%s', 'Delimiter', ';' );
        header.units    = strUnits{1};

        % DAQmx channel names (as programmed in NI MAX explorer)
        strDAQmx        = fgetl( fid );             
        strDAQmx        = textscan( strDAQmx, '%s', 'Delimiter', ';' );
        header.DAQch    = strDAQmx{1};

    case 'v2.0'     % v2.0 generated by ZE Recorder made in LabVIEW
        
        disp(['Reading header, fileformat ' fileFormat ' ...']) 
        
        % read 5 more lines of header
        strHeader = textscan( fid, '%s%s', 5, ...
                              'Delimiter', ';', ...
                              'HeaderLines', 1 );
                          
        header.fileFormat       = fileFormat;
        header.project          = char( strHeader{2}(1) );
        
        % make sure that if csv file was generated with german XP,
        % that the comma is replaced with a decimal point
        samplingRate            = strrep( strHeader{2}(2), ',', '.' );
        header.sRate            = str2double( samplingRate );

        header.description      = char( strHeader{2}(4) );
        header.nrOfSamples      = str2double( strHeader{2}(5) );
        header.operator         = char( strHeader{2}(3) );
                          
        % read header of data columns (they are part of the header)
        strChannels     = fgetl( fid );              %#ok<*NASGU>
        strChannels     = fgetl( fid );             
          
        % channel names
        strChannels     = fgetl( fid );             
        strChannels     = textscan( strChannels, '%s', 'Delimiter', ';' );
        header.channels = strChannels{1};

    otherwise
        
        disp('ERROR reading file header, unknown fileformat!') 
        
        % close file
        fclose( fid );
        
        % empty results are returned
        return
end



%% read data if required

switch readMode
    
    case 'whole'
        
        % format string

        strFormat = [];
        for i = 1:length( header.channels )
            strFormat = strcat( strFormat, '%f' );
        end

        % read data
       
        raw = zeros( header.nrOfSamples, length( header.channels ) );
        
        for i = 1:header.nrOfSamples
            
            tline = fgetl( fid );
            if ~ischar( tline )
                break
            else
                
                % make decimal separator internation if is german
                
                if contains(  tline, ','  )
                    tline = strrep( tline, ',', '.' );
                end
                
                datLine = textscan( tline, strFormat, 1, ...
                                     'Delimiter', ';', ...
                                     'CollectOutput', 1 );
                raw(i,:) = datLine{1};
                
            end
            
        end
        
        
        % convert array to cell array
        
        data = cell( 1, length( header.channels ) );

        for i = 1:length( header.channels )
            data{i} = raw(:,i);
        end

end

%% close file
fclose( fid );


